export const fakers = [
    {
      "GroupDefinitions/Type": "DIMENSION",
      "GroupDefinitions/Key": "SERVICE",
      "TimePeriod/Start": "2022-01-22",
      "TimePeriod/End": "2022-01-23",
      "Groups/0/Keys/0": "AWS CloudShell",
      "Groups/0/Metrics/BlendedCost/Amount": 4.25,
      "Groups/0/Metrics/BlendedCost/Unit": "USD",
      "Groups/1/Keys/0": "EC2 - Other",
      "Groups/1/Metrics/BlendedCost/Amount": 5,
      "Groups/1/Metrics/BlendedCost/Unit": "USD",
      "Groups/2/Keys/0": "Amazon Elastic Compute Cloud - Compute",
      "Groups/2/Metrics/BlendedCost/Amount": 3.5,
      "Groups/2/Metrics/BlendedCost/Unit": "USD",
      "Groups/3/Keys/0": "Amazon Simple Storage Service",
      "Groups/3/Metrics/BlendedCost/Amount": 3,
      "Groups/3/Metrics/BlendedCost/Unit": "USD",
      "Groups/4/Keys/0": "AWS CloudTrail",
      "Groups/4/Metrics/BlendedCost/Amount": 4.5,
      "Groups/4/Metrics/BlendedCost/Unit": "USD",
      "Estimated": false
    },
    {
      "GroupDefinitions/Type": "",
      "GroupDefinitions/Key": "",
      "TimePeriod/Start": "2022-01-23",
      "TimePeriod/End": "2022-01-24",
      "Groups/0/Keys/0": "AWS CloudShell",
      "Groups/0/Metrics/BlendedCost/Amount": 3.5,
      "Groups/0/Metrics/BlendedCost/Unit": "USD",
      "Groups/1/Keys/0": "EC2 - Other",
      "Groups/1/Metrics/BlendedCost/Amount": 4,
      "Groups/1/Metrics/BlendedCost/Unit": "USD",
      "Groups/2/Keys/0": "Amazon Elastic Compute Cloud - Compute",
      "Groups/2/Metrics/BlendedCost/Amount": 3.5,
      "Groups/2/Metrics/BlendedCost/Unit": "USD",
      "Groups/3/Keys/0": "Amazon Simple Storage Service",
      "Groups/3/Metrics/BlendedCost/Amount": 3,
      "Groups/3/Metrics/BlendedCost/Unit": "USD",
      "Groups/4/Keys/0": "AWS CloudTrail",
      "Groups/4/Metrics/BlendedCost/Amount": 4,
      "Groups/4/Metrics/BlendedCost/Unit": "USD",
      "Estimated": false
    },
    {
      "GroupDefinitions/Type": "",
      "GroupDefinitions/Key": "",
      "TimePeriod/Start": "2022-01-24",
      "TimePeriod/End": "2022-01-25",
      "Groups/0/Keys/0": "AWS CloudShell",
      "Groups/0/Metrics/BlendedCost/Amount": 4.5,
      "Groups/0/Metrics/BlendedCost/Unit": "USD",
      "Groups/1/Keys/0": "EC2 - Other",
      "Groups/1/Metrics/BlendedCost/Amount": 5,
      "Groups/1/Metrics/BlendedCost/Unit": "USD",
      "Groups/2/Keys/0": "Amazon Elastic Compute Cloud - Compute",
      "Groups/2/Metrics/BlendedCost/Amount": 3.25,
      "Groups/2/Metrics/BlendedCost/Unit": "USD",
      "Groups/3/Keys/0": "Amazon Simple Storage Service",
      "Groups/3/Metrics/BlendedCost/Amount": 4.5,
      "Groups/3/Metrics/BlendedCost/Unit": "USD",
      "Groups/4/Keys/0": "AWS CloudTrail",
      "Groups/4/Metrics/BlendedCost/Amount": 4.5,
      "Groups/4/Metrics/BlendedCost/Unit": "USD",
      "Estimated": false
    },
    {
      "GroupDefinitions/Type": "",
      "GroupDefinitions/Key": "",
      "TimePeriod/Start": "2022-01-25",
      "TimePeriod/End": "2022-01-26",
      "Groups/0/Keys/0": "AWS CloudShell",
      "Groups/0/Metrics/BlendedCost/Amount": 3.7,
      "Groups/0/Metrics/BlendedCost/Unit": "USD",
      "Groups/1/Keys/0": "EC2 - Other",
      "Groups/1/Metrics/BlendedCost/Amount": 5,
      "Groups/1/Metrics/BlendedCost/Unit": "USD",
      "Groups/2/Keys/0": "Amazon Elastic Compute Cloud - Compute",
      "Groups/2/Metrics/BlendedCost/Amount": 3.5,
      "Groups/2/Metrics/BlendedCost/Unit": "USD",
      "Groups/3/Keys/0": "Amazon Simple Storage Service",
      "Groups/3/Metrics/BlendedCost/Amount": 4,
      "Groups/3/Metrics/BlendedCost/Unit": "USD",
      "Groups/4/Keys/0": "AWS CloudTrail",
      "Groups/4/Metrics/BlendedCost/Amount": 5,
      "Groups/4/Metrics/BlendedCost/Unit": "USD",
      "Estimated": false
    },
    {
      "GroupDefinitions/Type": "",
      "GroupDefinitions/Key": "",
      "TimePeriod/Start": "2022-01-26",
      "TimePeriod/End": "2022-01-27",
      "Groups/0/Keys/0": "AWS CloudShell",
      "Groups/0/Metrics/BlendedCost/Amount": 3.4,
      "Groups/0/Metrics/BlendedCost/Unit": "USD",
      "Groups/1/Keys/0": "EC2 - Other",
      "Groups/1/Metrics/BlendedCost/Amount": 4.5,
      "Groups/1/Metrics/BlendedCost/Unit": "USD",
      "Groups/2/Keys/0": "Amazon Elastic Compute Cloud - Compute",
      "Groups/2/Metrics/BlendedCost/Amount": 3.7,
      "Groups/2/Metrics/BlendedCost/Unit": "USD",
      "Groups/3/Keys/0": "Amazon Simple Storage Service",
      "Groups/3/Metrics/BlendedCost/Amount": 4.2,
      "Groups/3/Metrics/BlendedCost/Unit": "USD",
      "Groups/4/Keys/0": "AWS CloudTrail",
      "Groups/4/Metrics/BlendedCost/Amount": 5.1,
      "Groups/4/Metrics/BlendedCost/Unit": "USD",
      "Estimated": false
    },
    {
      "GroupDefinitions/Type": "",
      "GroupDefinitions/Key": "",
      "TimePeriod/Start": "2022-01-27",
      "TimePeriod/End": "2022-01-28",
      "Groups/0/Keys/0": "AWS CloudShell",
      "Groups/0/Metrics/BlendedCost/Amount": 3.2,
      "Groups/0/Metrics/BlendedCost/Unit": "USD",
      "Groups/1/Keys/0": "EC2 - Other",
      "Groups/1/Metrics/BlendedCost/Amount": 4.5,
      "Groups/1/Metrics/BlendedCost/Unit": "USD",
      "Groups/2/Keys/0": "Amazon Elastic Compute Cloud - Compute",
      "Groups/2/Metrics/BlendedCost/Amount": 3.3,
      "Groups/2/Metrics/BlendedCost/Unit": "USD",
      "Groups/3/Keys/0": "Amazon Simple Storage Service",
      "Groups/3/Metrics/BlendedCost/Amount": 4,
      "Groups/3/Metrics/BlendedCost/Unit": "USD",
      "Groups/4/Keys/0": "AWS CloudTrail",
      "Groups/4/Metrics/BlendedCost/Amount": 5.8,
      "Groups/4/Metrics/BlendedCost/Unit": "USD",
      "Estimated": false
    },
    {
      "GroupDefinitions/Type": "",
      "GroupDefinitions/Key": "",
      "TimePeriod/Start": "2022-01-28",
      "TimePeriod/End": "2022-01-29",
      "Groups/0/Keys/0": "AWS CloudShell",
      "Groups/0/Metrics/BlendedCost/Amount": 3.75,
      "Groups/0/Metrics/BlendedCost/Unit": "USD",
      "Groups/1/Keys/0": "EC2 - Other",
      "Groups/1/Metrics/BlendedCost/Amount": 4,
      "Groups/1/Metrics/BlendedCost/Unit": "USD",
      "Groups/2/Keys/0": "Amazon Elastic Compute Cloud - Compute",
      "Groups/2/Metrics/BlendedCost/Amount": 3.5,
      "Groups/2/Metrics/BlendedCost/Unit": "USD",
      "Groups/3/Keys/0": "Amazon Simple Storage Service",
      "Groups/3/Metrics/BlendedCost/Amount": 4.5,
      "Groups/3/Metrics/BlendedCost/Unit": "USD",
      "Groups/4/Keys/0": "AWS CloudTrail",
      "Groups/4/Metrics/BlendedCost/Amount": 5,
      "Groups/4/Metrics/BlendedCost/Unit": "USD",
      "Estimated": false
    },
    {
      "GroupDefinitions/Type": "",
      "GroupDefinitions/Key": "",
      "TimePeriod/Start": "2022-01-29",
      "TimePeriod/End": "2022-01-30",
      "Groups/0/Keys/0": "AWS CloudShell",
      "Groups/0/Metrics/BlendedCost/Amount": 4.15,
      "Groups/0/Metrics/BlendedCost/Unit": "USD",
      "Groups/1/Keys/0": "EC2 - Other",
      "Groups/1/Metrics/BlendedCost/Amount": 4.5,
      "Groups/1/Metrics/BlendedCost/Unit": "USD",
      "Groups/2/Keys/0": "Amazon Elastic Compute Cloud - Compute",
      "Groups/2/Metrics/BlendedCost/Amount": 3.75,
      "Groups/2/Metrics/BlendedCost/Unit": "USD",
      "Groups/3/Keys/0": "Amazon Simple Storage Service",
      "Groups/3/Metrics/BlendedCost/Amount": 4.7,
      "Groups/3/Metrics/BlendedCost/Unit": "USD",
      "Groups/4/Keys/0": "AWS CloudTrail",
      "Groups/4/Metrics/BlendedCost/Amount": 5.05,
      "Groups/4/Metrics/BlendedCost/Unit": "USD",
      "Estimated": false
    },
    {
      "GroupDefinitions/Type": "",
      "GroupDefinitions/Key": "",
      "TimePeriod/Start": "2022-01-31",
      "TimePeriod/End": "2022-02-01",
      "Groups/0/Keys/0": "AWS CloudShell",
      "Groups/0/Metrics/BlendedCost/Amount": 3.5,
      "Groups/0/Metrics/BlendedCost/Unit": "USD",
      "Groups/1/Keys/0": "EC2 - Other",
      "Groups/1/Metrics/BlendedCost/Amount": 5.1,
      "Groups/1/Metrics/BlendedCost/Unit": "USD",
      "Groups/2/Keys/0": "Amazon Elastic Compute Cloud - Compute",
      "Groups/2/Metrics/BlendedCost/Amount": 4.25,
      "Groups/2/Metrics/BlendedCost/Unit": "USD",
      "Groups/3/Keys/0": "Amazon Simple Storage Service",
      "Groups/3/Metrics/BlendedCost/Amount": 5.8,
      "Groups/3/Metrics/BlendedCost/Unit": "USD",
      "Groups/4/Keys/0": "AWS CloudTrail",
      "Groups/4/Metrics/BlendedCost/Amount": 7.25,
      "Groups/4/Metrics/BlendedCost/Unit": "USD",
      "Estimated": false
    },
    {
      "GroupDefinitions/Type": "",
      "GroupDefinitions/Key": "",
      "TimePeriod/Start": "2022-02-01",
      "TimePeriod/End": "2022-02-02",
      "Groups/0/Keys/0": "AWS CloudShell",
      "Groups/0/Metrics/BlendedCost/Amount": 6.5,
      "Groups/0/Metrics/BlendedCost/Unit": "USD",
      "Groups/1/Keys/0": "EC2 - Other",
      "Groups/1/Metrics/BlendedCost/Amount": 8.2,
      "Groups/1/Metrics/BlendedCost/Unit": "USD",
      "Groups/2/Keys/0": "Amazon Elastic Compute Cloud - Compute",
      "Groups/2/Metrics/BlendedCost/Amount": 7.85,
      "Groups/2/Metrics/BlendedCost/Unit": "USD",
      "Groups/3/Keys/0": "Amazon Simple Storage Service",
      "Groups/3/Metrics/BlendedCost/Amount": 9.4,
      "Groups/3/Metrics/BlendedCost/Unit": "USD",
      "Groups/4/Keys/0": "AWS CloudTrail",
      "Groups/4/Metrics/BlendedCost/Amount": 5.85,
      "Groups/4/Metrics/BlendedCost/Unit": "USD",
      "Estimated": false
    },
    {
      "GroupDefinitions/Type": "",
      "GroupDefinitions/Key": "",
      "TimePeriod/Start": "2022-02-02",
      "TimePeriod/End": "2022-02-03",
      "Groups/0/Keys/0": "AWS CloudShell",
      "Groups/0/Metrics/BlendedCost/Amount": 6.5,
      "Groups/0/Metrics/BlendedCost/Unit": "USD",
      "Groups/1/Keys/0": "EC2 - Other",
      "Groups/1/Metrics/BlendedCost/Amount": 8.2,
      "Groups/1/Metrics/BlendedCost/Unit": "USD",
      "Groups/2/Keys/0": "Amazon Elastic Compute Cloud - Compute",
      "Groups/2/Metrics/BlendedCost/Amount": 7.85,
      "Groups/2/Metrics/BlendedCost/Unit": "USD",
      "Groups/3/Keys/0": "Amazon Simple Storage Service",
      "Groups/3/Metrics/BlendedCost/Amount": 9.4,
      "Groups/3/Metrics/BlendedCost/Unit": "USD",
      "Groups/4/Keys/0": "AWS CloudTrail",
      "Groups/4/Metrics/BlendedCost/Amount": 5.85,
      "Groups/4/Metrics/BlendedCost/Unit": "USD",
      "Estimated": false
    },
    {
      "GroupDefinitions/Type": "",
      "GroupDefinitions/Key": "",
      "TimePeriod/Start": "2022-02-03",
      "TimePeriod/End": "2022-02-04",
      "Groups/0/Keys/0": "AWS CloudShell",
      "Groups/0/Metrics/BlendedCost/Amount": 6.1,
      "Groups/0/Metrics/BlendedCost/Unit": "USD",
      "Groups/1/Keys/0": "EC2 - Other",
      "Groups/1/Metrics/BlendedCost/Amount": 7.8,
      "Groups/1/Metrics/BlendedCost/Unit": "USD",
      "Groups/2/Keys/0": "Amazon Elastic Compute Cloud - Compute",
      "Groups/2/Metrics/BlendedCost/Amount": 6.35,
      "Groups/2/Metrics/BlendedCost/Unit": "USD",
      "Groups/3/Keys/0": "Amazon Simple Storage Service",
      "Groups/3/Metrics/BlendedCost/Amount": 8.9,
      "Groups/3/Metrics/BlendedCost/Unit": "USD",
      "Groups/4/Keys/0": "AWS CloudTrail",
      "Groups/4/Metrics/BlendedCost/Amount": 6.1,
      "Groups/4/Metrics/BlendedCost/Unit": "USD",
      "Estimated": false
    },
    {
      "GroupDefinitions/Type": "",
      "GroupDefinitions/Key": "",
      "TimePeriod/Start": "2022-02-04",
      "TimePeriod/End": "2022-02-05",
      "Groups/0/Keys/0": "AWS CloudShell",
      "Groups/0/Metrics/BlendedCost/Amount": 7.2,
      "Groups/0/Metrics/BlendedCost/Unit": "USD",
      "Groups/1/Keys/0": "EC2 - Other",
      "Groups/1/Metrics/BlendedCost/Amount": 9.1,
      "Groups/1/Metrics/BlendedCost/Unit": "USD",
      "Groups/2/Keys/0": "Amazon Elastic Compute Cloud - Compute",
      "Groups/2/Metrics/BlendedCost/Amount": 8.45,
      "Groups/2/Metrics/BlendedCost/Unit": "USD",
      "Groups/3/Keys/0": "Amazon Simple Storage Service",
      "Groups/3/Metrics/BlendedCost/Amount": 10,
      "Groups/3/Metrics/BlendedCost/Unit": "USD",
      "Groups/4/Keys/0": "AWS CloudTrail",
      "Groups/4/Metrics/BlendedCost/Amount": 7.35,
      "Groups/4/Metrics/BlendedCost/Unit": "USD",
      "Estimated": false
    },
    {
      "GroupDefinitions/Type": "",
      "GroupDefinitions/Key": "",
      "TimePeriod/Start": "2022-02-05",
      "TimePeriod/End": "2022-02-06",
      "Groups/0/Keys/0": "AWS CloudShell",
      "Groups/0/Metrics/BlendedCost/Amount": 8.4,
      "Groups/0/Metrics/BlendedCost/Unit": "USD",
      "Groups/1/Keys/0": "",
      "Groups/1/Metrics/BlendedCost/Amount": "",
      "Groups/1/Metrics/BlendedCost/Unit": "",
      "Groups/2/Keys/0": "",
      "Groups/2/Metrics/BlendedCost/Amount": "",
      "Groups/2/Metrics/BlendedCost/Unit": "",
      "Groups/3/Keys/0": "",
      "Groups/3/Metrics/BlendedCost/Amount": "",
      "Groups/3/Metrics/BlendedCost/Unit": "",
      "Groups/4/Keys/0": "",
      "Groups/4/Metrics/BlendedCost/Amount": "",
      "Groups/4/Metrics/BlendedCost/Unit": "",
      "Estimated": false
    },
    {
      "GroupDefinitions/Type": "",
      "GroupDefinitions/Key": "",
      "TimePeriod/Start": "2022-02-06",
      "TimePeriod/End": "2022-02-07",
      "Groups/0/Keys/0": "AWS CloudShell",
      "Groups/0/Metrics/BlendedCost/Amount": 6.75,
      "Groups/0/Metrics/BlendedCost/Unit": "USD",
      "Groups/1/Keys/0": "EC2 - Other",
      "Groups/1/Metrics/BlendedCost/Amount": 7.3,
      "Groups/1/Metrics/BlendedCost/Unit": "USD",
      "Groups/2/Keys/0": "Amazon Elastic Compute Cloud - Compute",
      "Groups/2/Metrics/BlendedCost/Amount": 8.55,
      "Groups/2/Metrics/BlendedCost/Unit": "USD",
      "Groups/3/Keys/0": "Amazon Simple Storage Service",
      "Groups/3/Metrics/BlendedCost/Amount": 9.1,
      "Groups/3/Metrics/BlendedCost/Unit": "USD",
      "Groups/4/Keys/0": "AWS CloudTrail",
      "Groups/4/Metrics/BlendedCost/Amount": 7.2,
      "Groups/4/Metrics/BlendedCost/Unit": "USD",
      "Estimated": false
    },
    {
      "GroupDefinitions/Type": "",
      "GroupDefinitions/Key": "",
      "TimePeriod/Start": "2022-02-07",
      "TimePeriod/End": "2022-02-08",
      "Groups/0/Keys/0": "AWS CloudShell",
      "Groups/0/Metrics/BlendedCost/Amount": 7.5,
      "Groups/0/Metrics/BlendedCost/Unit": "USD",
      "Groups/1/Keys/0": "EC2 - Other",
      "Groups/1/Metrics/BlendedCost/Amount": 8,
      "Groups/1/Metrics/BlendedCost/Unit": "USD",
      "Groups/2/Keys/0": "Amazon Elastic Compute Cloud - Compute",
      "Groups/2/Metrics/BlendedCost/Amount": 7.75,
      "Groups/2/Metrics/BlendedCost/Unit": "USD",
      "Groups/3/Keys/0": "Amazon Simple Storage Service",
      "Groups/3/Metrics/BlendedCost/Amount": 9.4,
      "Groups/3/Metrics/BlendedCost/Unit": "USD",
      "Groups/4/Keys/0": "AWS CloudTrail",
      "Groups/4/Metrics/BlendedCost/Amount": 6.55,
      "Groups/4/Metrics/BlendedCost/Unit": "USD",
      "Estimated": false
    },
    {
      "GroupDefinitions/Type": "",
      "GroupDefinitions/Key": "",
      "TimePeriod/Start": "2022-02-08",
      "TimePeriod/End": "2022-02-09",
      "Groups/0/Keys/0": "AWS CloudShell",
      "Groups/0/Metrics/BlendedCost/Amount": 6.3,
      "Groups/0/Metrics/BlendedCost/Unit": "USD",
      "Groups/1/Keys/0": "EC2 - Other",
      "Groups/1/Metrics/BlendedCost/Amount": 7.85,
      "Groups/1/Metrics/BlendedCost/Unit": "USD",
      "Groups/2/Keys/0": "Amazon Elastic Compute Cloud - Compute",
      "Groups/2/Metrics/BlendedCost/Amount": 6.1,
      "Groups/2/Metrics/BlendedCost/Unit": "USD",
      "Groups/3/Keys/0": "Amazon Simple Storage Service",
      "Groups/3/Metrics/BlendedCost/Amount": 8.65,
      "Groups/3/Metrics/BlendedCost/Unit": "USD",
      "Groups/4/Keys/0": "AWS CloudTrail",
      "Groups/4/Metrics/BlendedCost/Amount": 7.65,
      "Groups/4/Metrics/BlendedCost/Unit": "USD",
      "Estimated": false
    },
    {
      "GroupDefinitions/Type": "",
      "GroupDefinitions/Key": "",
      "TimePeriod/Start": "2022-02-09",
      "TimePeriod/End": "2022-02-10",
      "Groups/0/Keys/0": "AWS CloudShell",
      "Groups/0/Metrics/BlendedCost/Amount": 7.1,
      "Groups/0/Metrics/BlendedCost/Unit": "USD",
      "Groups/1/Keys/0": "EC2 - Other",
      "Groups/1/Metrics/BlendedCost/Amount": 8.5,
      "Groups/1/Metrics/BlendedCost/Unit": "USD",
      "Groups/2/Keys/0": "Amazon Elastic Compute Cloud - Compute",
      "Groups/2/Metrics/BlendedCost/Amount": 8.2,
      "Groups/2/Metrics/BlendedCost/Unit": "USD",
      "Groups/3/Keys/0": "Amazon Simple Storage Service",
      "Groups/3/Metrics/BlendedCost/Amount": 9.9,
      "Groups/3/Metrics/BlendedCost/Unit": "USD",
      "Groups/4/Keys/0": "AWS CloudTrail",
      "Groups/4/Metrics/BlendedCost/Amount": 6.4,
      "Groups/4/Metrics/BlendedCost/Unit": "USD",
      "Estimated": false
    },
    {
      "GroupDefinitions/Type": "",
      "GroupDefinitions/Key": "",
      "TimePeriod/Start": "2022-02-10",
      "TimePeriod/End": "2022-02-11",
      "Groups/0/Keys/0": "AWS CloudShell",
      "Groups/0/Metrics/BlendedCost/Amount": 7.1,
      "Groups/0/Metrics/BlendedCost/Unit": "USD",
      "Groups/1/Keys/0": "EC2 - Other",
      "Groups/1/Metrics/BlendedCost/Amount": 8.5,
      "Groups/1/Metrics/BlendedCost/Unit": "USD",
      "Groups/2/Keys/0": "Amazon Elastic Compute Cloud - Compute",
      "Groups/2/Metrics/BlendedCost/Amount": 8.2,
      "Groups/2/Metrics/BlendedCost/Unit": "USD",
      "Groups/3/Keys/0": "Amazon Simple Storage Service",
      "Groups/3/Metrics/BlendedCost/Amount": 9.9,
      "Groups/3/Metrics/BlendedCost/Unit": "USD",
      "Groups/4/Keys/0": "AWS CloudTrail",
      "Groups/4/Metrics/BlendedCost/Amount": 6.4,
      "Groups/4/Metrics/BlendedCost/Unit": "USD",
      "Estimated": false
    },
    {
      "GroupDefinitions/Type": "",
      "GroupDefinitions/Key": "",
      "TimePeriod/Start": "2022-02-11",
      "TimePeriod/End": "2022-02-12",
      "Groups/0/Keys/0": "AWS CloudShell",
      "Groups/0/Metrics/BlendedCost/Amount": 6.3,
      "Groups/0/Metrics/BlendedCost/Unit": "USD",
      "Groups/1/Keys/0": "EC2 - Other",
      "Groups/1/Metrics/BlendedCost/Amount": 7.85,
      "Groups/1/Metrics/BlendedCost/Unit": "USD",
      "Groups/2/Keys/0": "Amazon Elastic Compute Cloud - Compute",
      "Groups/2/Metrics/BlendedCost/Amount": 6.1,
      "Groups/2/Metrics/BlendedCost/Unit": "USD",
      "Groups/3/Keys/0": "Amazon Simple Storage Service",
      "Groups/3/Metrics/BlendedCost/Amount": 8.65,
      "Groups/3/Metrics/BlendedCost/Unit": "USD",
      "Groups/4/Keys/0": "AWS CloudTrail",
      "Groups/4/Metrics/BlendedCost/Amount": 8.35,
      "Groups/4/Metrics/BlendedCost/Unit": "USD",
      "Estimated": false
    },
    {
      "GroupDefinitions/Type": "",
      "GroupDefinitions/Key": "",
      "TimePeriod/Start": "2022-02-12",
      "TimePeriod/End": "2022-02-13",
      "Groups/0/Keys/0": "AWS CloudShell",
      "Groups/0/Metrics/BlendedCost/Amount": 8.9,
      "Groups/0/Metrics/BlendedCost/Unit": "USD",
      "Groups/1/Keys/0": "EC2 - Other",
      "Groups/1/Metrics/BlendedCost/Amount": 9.2,
      "Groups/1/Metrics/BlendedCost/Unit": "USD",
      "Groups/2/Keys/0": "Amazon Elastic Compute Cloud - Compute",
      "Groups/2/Metrics/BlendedCost/Amount": 9.55,
      "Groups/2/Metrics/BlendedCost/Unit": "USD",
      "Groups/3/Keys/0": "Amazon Simple Storage Service",
      "Groups/3/Metrics/BlendedCost/Amount": 10.4,
      "Groups/3/Metrics/BlendedCost/Unit": "USD",
      "Groups/4/Keys/0": "AWS CloudTrail",
      "Groups/4/Metrics/BlendedCost/Amount": 5.7,
      "Groups/4/Metrics/BlendedCost/Unit": "USD",
      "Estimated": false
    },
    {
      "GroupDefinitions/Type": "",
      "GroupDefinitions/Key": "",
      "TimePeriod/Start": "2022-02-13",
      "TimePeriod/End": "2022-02-14",
      "Groups/0/Keys/0": "AWS CloudShell",
      "Groups/0/Metrics/BlendedCost/Amount": 7.8,
      "Groups/0/Metrics/BlendedCost/Unit": "USD",
      "Groups/1/Keys/0": "EC2 - Other",
      "Groups/1/Metrics/BlendedCost/Amount": 6.6,
      "Groups/1/Metrics/BlendedCost/Unit": "USD",
      "Groups/2/Keys/0": "Amazon Elastic Compute Cloud - Compute",
      "Groups/2/Metrics/BlendedCost/Amount": 8.15,
      "Groups/2/Metrics/BlendedCost/Unit": "USD",
      "Groups/3/Keys/0": "Amazon Simple Storage Service",
      "Groups/3/Metrics/BlendedCost/Amount": 9.7,
      "Groups/3/Metrics/BlendedCost/Unit": "USD",
      "Groups/4/Keys/0": "AWS CloudTrail",
      "Groups/4/Metrics/BlendedCost/Amount": 7.25,
      "Groups/4/Metrics/BlendedCost/Unit": "USD",
      "Estimated": false
    },
    {
      "GroupDefinitions/Type": "",
      "GroupDefinitions/Key": "",
      "TimePeriod/Start": "2022-02-14",
      "TimePeriod/End": "2022-02-15",
      "Groups/0/Keys/0": "AWS CloudShell",
      "Groups/0/Metrics/BlendedCost/Amount": 8.3,
      "Groups/0/Metrics/BlendedCost/Unit": "USD",
      "Groups/1/Keys/0": "EC2 - Other",
      "Groups/1/Metrics/BlendedCost/Amount": 9.5,
      "Groups/1/Metrics/BlendedCost/Unit": "USD",
      "Groups/2/Keys/0": "Amazon Elastic Compute Cloud - Compute",
      "Groups/2/Metrics/BlendedCost/Amount": 8.85,
      "Groups/2/Metrics/BlendedCost/Unit": "USD",
      "Groups/3/Keys/0": "Amazon Simple Storage Service",
      "Groups/3/Metrics/BlendedCost/Amount": 9.4,
      "Groups/3/Metrics/BlendedCost/Unit": "USD",
      "Groups/4/Keys/0": "AWS CloudTrail",
      "Groups/4/Metrics/BlendedCost/Amount": 6.85,
      "Groups/4/Metrics/BlendedCost/Unit": "USD",
      "Estimated": false
    },
    {
      "GroupDefinitions/Type": "",
      "GroupDefinitions/Key": "",
      "TimePeriod/Start": "2022-02-15",
      "TimePeriod/End": "2022-02-16",
      "Groups/0/Keys/0": "AWS CloudShell",
      "Groups/0/Metrics/BlendedCost/Amount": 8.3,
      "Groups/0/Metrics/BlendedCost/Unit": "USD",
      "Groups/1/Keys/0": "EC2 - Other",
      "Groups/1/Metrics/BlendedCost/Amount": 9.5,
      "Groups/1/Metrics/BlendedCost/Unit": "USD",
      "Groups/2/Keys/0": "Amazon Elastic Compute Cloud - Compute",
      "Groups/2/Metrics/BlendedCost/Amount": 8.85,
      "Groups/2/Metrics/BlendedCost/Unit": "USD",
      "Groups/3/Keys/0": "Amazon Simple Storage Service",
      "Groups/3/Metrics/BlendedCost/Amount": 9.4,
      "Groups/3/Metrics/BlendedCost/Unit": "USD",
      "Groups/4/Keys/0": "AWS CloudTrail",
      "Groups/4/Metrics/BlendedCost/Amount": 6.85,
      "Groups/4/Metrics/BlendedCost/Unit": "USD",
      "Estimated": false
    },
    {
      "GroupDefinitions/Type": "",
      "GroupDefinitions/Key": "",
      "TimePeriod/Start": "2022-02-16",
      "TimePeriod/End": "2022-02-17",
      "Groups/0/Keys/0": "AWS CloudShell",
      "Groups/0/Metrics/BlendedCost/Amount": 6.6,
      "Groups/0/Metrics/BlendedCost/Unit": "USD",
      "Groups/1/Keys/0": "EC2 - Other",
      "Groups/1/Metrics/BlendedCost/Amount": 7.9,
      "Groups/1/Metrics/BlendedCost/Unit": "USD",
      "Groups/2/Keys/0": "Amazon Elastic Compute Cloud - Compute",
      "Groups/2/Metrics/BlendedCost/Amount": 6.35,
      "Groups/2/Metrics/BlendedCost/Unit": "USD",
      "Groups/3/Keys/0": "Amazon Simple Storage Service",
      "Groups/3/Metrics/BlendedCost/Amount": 9.8,
      "Groups/3/Metrics/BlendedCost/Unit": "USD",
      "Groups/4/Keys/0": "AWS CloudTrail",
      "Groups/4/Metrics/BlendedCost/Amount": 6.1,
      "Groups/4/Metrics/BlendedCost/Unit": "USD",
      "Estimated": false
    },
    {
      "GroupDefinitions/Type": "",
      "GroupDefinitions/Key": "",
      "TimePeriod/Start": "2022-02-17",
      "TimePeriod/End": "2022-02-18",
      "Groups/0/Keys/0": "AWS CloudShell",
      "Groups/0/Metrics/BlendedCost/Amount": 9.1,
      "Groups/0/Metrics/BlendedCost/Unit": "USD",
      "Groups/1/Keys/0": "EC2 - Other",
      "Groups/1/Metrics/BlendedCost/Amount": 9.8,
      "Groups/1/Metrics/BlendedCost/Unit": "USD",
      "Groups/2/Keys/0": "Amazon Elastic Compute Cloud - Compute",
      "Groups/2/Metrics/BlendedCost/Amount": 9.15,
      "Groups/2/Metrics/BlendedCost/Unit": "USD",
      "Groups/3/Keys/0": "Amazon Simple Storage Service",
      "Groups/3/Metrics/BlendedCost/Amount": 10.5,
      "Groups/3/Metrics/BlendedCost/Unit": "USD",
      "Groups/4/Keys/0": "AWS CloudTrail",
      "Groups/4/Metrics/BlendedCost/Amount": 7.95,
      "Groups/4/Metrics/BlendedCost/Unit": "USD",
      "Estimated": false
    },
    {
      "GroupDefinitions/Type": "",
      "GroupDefinitions/Key": "",
      "TimePeriod/Start": "2022-02-18",
      "TimePeriod/End": "2022-02-19",
      "Groups/0/Keys/0": "AWS CloudShell",
      "Groups/0/Metrics/BlendedCost/Amount": 6.9,
      "Groups/0/Metrics/BlendedCost/Unit": "USD",
      "Groups/1/Keys/0": "EC2 - Other",
      "Groups/1/Metrics/BlendedCost/Amount": 8.1,
      "Groups/1/Metrics/BlendedCost/Unit": "USD",
      "Groups/2/Keys/0": "Amazon Elastic Compute Cloud - Compute",
      "Groups/2/Metrics/BlendedCost/Amount": 6.75,
      "Groups/2/Metrics/BlendedCost/Unit": "USD",
      "Groups/3/Keys/0": "Amazon Simple Storage Service",
      "Groups/3/Metrics/BlendedCost/Amount": 9.2,
      "Groups/3/Metrics/BlendedCost/Unit": "USD",
      "Groups/4/Keys/0": "AWS CloudTrail",
      "Groups/4/Metrics/BlendedCost/Amount": 7.3,
      "Groups/4/Metrics/BlendedCost/Unit": "USD",
      "Estimated": false
    },
    {
      "GroupDefinitions/Type": "",
      "GroupDefinitions/Key": "",
      "TimePeriod/Start": "2022-02-19",
      "TimePeriod/End": "2022-02-20",
      "Groups/0/Keys/0": "AWS CloudShell",
      "Groups/0/Metrics/BlendedCost/Amount": 8.2,
      "Groups/0/Metrics/BlendedCost/Unit": "USD",
      "Groups/1/Keys/0": "EC2 - Other",
      "Groups/1/Metrics/BlendedCost/Amount": 7.5,
      "Groups/1/Metrics/BlendedCost/Unit": "USD",
      "Groups/2/Keys/0": "Amazon Elastic Compute Cloud - Compute",
      "Groups/2/Metrics/BlendedCost/Amount": 8.85,
      "Groups/2/Metrics/BlendedCost/Unit": "USD",
      "Groups/3/Keys/0": "Amazon Simple Storage Service",
      "Groups/3/Metrics/BlendedCost/Amount": 9.8,
      "Groups/3/Metrics/BlendedCost/Unit": "USD",
      "Groups/4/Keys/0": "AWS CloudTrail",
      "Groups/4/Metrics/BlendedCost/Amount": 7.15,
      "Groups/4/Metrics/BlendedCost/Unit": "USD",
      "Estimated": false
    },
    {
      "GroupDefinitions/Type": "",
      "GroupDefinitions/Key": "",
      "TimePeriod/Start": "2022-02-20",
      "TimePeriod/End": "2022-02-21",
      "Groups/0/Keys/0": "AWS CloudShell",
      "Groups/0/Metrics/BlendedCost/Amount": 8.2,
      "Groups/0/Metrics/BlendedCost/Unit": "USD",
      "Groups/1/Keys/0": "EC2 - Other",
      "Groups/1/Metrics/BlendedCost/Amount": 7.5,
      "Groups/1/Metrics/BlendedCost/Unit": "USD",
      "Groups/2/Keys/0": "Amazon Elastic Compute Cloud - Compute",
      "Groups/2/Metrics/BlendedCost/Amount": 8.85,
      "Groups/2/Metrics/BlendedCost/Unit": "USD",
      "Groups/3/Keys/0": "Amazon Simple Storage Service",
      "Groups/3/Metrics/BlendedCost/Amount": 9.8,
      "Groups/3/Metrics/BlendedCost/Unit": "USD",
      "Groups/4/Keys/0": "AWS CloudTrail",
      "Groups/4/Metrics/BlendedCost/Amount": 7.15,
      "Groups/4/Metrics/BlendedCost/Unit": "USD",
      "Estimated": false
    },
    {
      "GroupDefinitions/Type": "",
      "GroupDefinitions/Key": "",
      "TimePeriod/Start": "2022-02-21",
      "TimePeriod/End": "2022-02-22",
      "Groups/0/Keys/0": "AWS CloudShell",
      "Groups/0/Metrics/BlendedCost/Amount": 9.1,
      "Groups/0/Metrics/BlendedCost/Unit": "USD",
      "Groups/1/Keys/0": "EC2 - Other",
      "Groups/1/Metrics/BlendedCost/Amount": 8.3,
      "Groups/1/Metrics/BlendedCost/Unit": "USD",
      "Groups/2/Keys/0": "Amazon Elastic Compute Cloud - Compute",
      "Groups/2/Metrics/BlendedCost/Amount": 6.95,
      "Groups/2/Metrics/BlendedCost/Unit": "USD",
      "Groups/3/Keys/0": "Amazon Simple Storage Service",
      "Groups/3/Metrics/BlendedCost/Amount": 10.2,
      "Groups/3/Metrics/BlendedCost/Unit": "USD",
      "Groups/4/Keys/0": "AWS CloudTrail",
      "Groups/4/Metrics/BlendedCost/Amount": 8.7,
      "Groups/4/Metrics/BlendedCost/Unit": "USD",
      "Estimated": false
    }
  ]